import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { ExpenseProvider } from '@/context/Expense';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={montserrat.className}>
      <body>
        <ExpenseProvider>{children}</ExpenseProvider>
      </body>
    </html>
  );
}
